name: ActionBarAPI-Plus
version: '1.0'
main: com.codingguru.actionBarAPI.testplugin.Main
api-version: '1.13'
description: ActionBarAPI-Plus
author: codingguru

commands:
  actionbarapiplus:
    description: ActionBarAPI+ commands
    usage: /actionbarapiplus <subcommand>
    permission: actionbarapiplus.runtest
